name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - name: version
        run: npm version minor
        with:
          token: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
        working-directory: ./
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
